### ISSUE TITLE
New representation of rotations: Modified Rodrigues Parameters

### ISSUE THREAD

**Issue by AlexanderFabisch** [dfki-ric/pytransform3d#140]
More information:

* https://ntrs.nasa.gov/api/citations/19960035754/downloads/19960035754.pdf
* https://link.springer.com/article/10.1007/s10851-017-0765-x
* http://malcolmdshuster.com/Pub_1993h_J_Repsurv_scan.pdf

**Comment by Mechazo11** [comment]
@AlexanderFabisch I am interested in helping.

**Comment by Mechazo11** [comment]
https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.transform.Rotation.from_mrp.html

**Comment by AlexanderFabisch** [comment]
Hi @Mechazo11,

that would be great! Let me know how I can assist you with getting started.
