### ISSUE TITLE
Documentation link shows 404 error

### ISSUE THREAD

**Issue by Mechazo11** [dfki-ric/pytransform3d#190]
Dear @AlexanderFabisch 

The website containing the API documentation shows 404 error. 
URL https://rock-learning.github.io/pytransform3d/

Could you take a look at it?

With best regards,
Mechazo11

**Comment by AlexanderFabisch** [comment]
Hi, where did you find the link? I moved it to https://dfki-ric.github.io/pytransform3d/ . So the old link needs to be updated.

**Comment by AlexanderFabisch** [comment]
I assume you were following the links of the readme on the master branch. These have been fixed with 1.14.0.

**Comment by Mechazo11** [comment]
@AlexanderFabisch Thank you very much for fixing the link. Yes, I was following the URL from the readme file.
