### ISSUE TITLE
draw TUM pose format using quaternion

### ISSUE THREAD

**Issue by arenas7307979** [dfki-ric/pytransform3d#197]
hii, 
I have seen the example of drawing through Euler Angle, 
if there is a way to directly draw path use quaternion or
convert function active_matrix_from_extrinsic_quaternion?

tum is pose format :  tx ty tz qx qy qz qw

![image](https://user-images.githubusercontent.com/5019568/190054192-899d174a-cae7-4c77-9267-627da4fd2bf4.png)

example:
https://github.com/dfki-ric/pytransform3d/blob/master/examples/plots/plot_euler_angles.py

**Comment by arenas7307979** [comment]
p = np.array([2.0, 0.0, 0.0])
euler = [0, 0, 0]
euler[axis] = angle
R = pr.matrix_from_quaternion([1,0,0,0])
# R = pr.active_matrix_from_intrinsic_euler_xyz(euler)
pr.plot_basis(ax, R, p)

**Comment by AlexanderFabisch** [comment]
I'm a bit confused, but I guess you are looking for something like this: https://dfki-ric.github.io/pytransform3d/_auto_examples/plots/plot_camera_trajectory.html#sphx-glr-auto-examples-plots-plot-camera-trajectory-py
