### ISSUE TITLE
Links in online documentation broken

### ISSUE THREAD

**Issue by joeda** [dfki-ric/pytransform3d#202]
In https://dfki-ric.github.io/pytransform3d/camera.html none of the links work, for example

https://dfki-ric.github.io/examples/plots/plot_camera_3d.py

or

https://dfki-ric.github.io/examples/plots/plot_camera_trajectory.hires.png

In a locally generated `doc` (as instructed in the README), those files exist

**Comment by AlexanderFabisch** [comment]
Thanks for reporting, I will look into this in the next days. If you like, you can also make a pull request to the branch gh-pages.

**Comment by AlexanderFabisch** [comment]
OK, it was a bit more difficult than I thought. `plot_directive` generated downloadable files in a folder that I didn't copy. I couldn't change the folder so I removed the links and included source code at places where it's needed. It should look similar to last time it when it was working.
