### ISSUE TITLE
Use of deprecated numpy.int

### ISSUE THREAD

**Issue by perkomvik** [dfki-ric/pytransform3d#204]
Hi, and thanks for the great library!

I get an error when using numpy version > 1.20 when using the `plot_trajectory` method in the `plot_utils` library: 

> AttributeError: module 'numpy' has no attribute 'int'. Did you mean: 'inf'?

This error is triggered at 
https://github.com/dfki-ric/pytransform3d/blob/b0f391153c6e15c4cceb9fcc50ed0ef3c8cefea8/pytransform3d/plot_utils/_artists.py#L232-L233

Use of numpy.int is deprecated as of numpy 1.20: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

**Comment by AlexanderFabisch** [comment]
Hi @perkomvik ,

thanks for letting me know. I fixed it in a41eddf145181f9db2bc779bad8a23b41f9f59cc at the develop branch and it will be part of the next release.
