### ISSUE TITLE
Implement direct conversion between quaternions and euler angles in any sequence

### ISSUE THREAD

**Issue by evbernardes** [dfki-ric/pytransform3d#207]
I recently published a [paper (open access)](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0276302) on a direct conversion between quaternions and euler angles in any sequence, that is a lot simpler to implement, faster to compute and does not need an intermediate step converting it to a matrix.

Since its publication, it has already been merged into [Scipy](https://github.com/scipy/scipy/pull/17392#issuecomment-1341593229), replacing the existing method, and it is also now part of [Sympy](https://github.com/sympy/sympy/pull/24358).

Since the original Scipy `Rotation.as_euler` method was used as an inspiration for `_general_intrinsic_euler_from_active_matrix`, the new direct method could be a nice addition to this library.

**Comment by AlexanderFabisch** [comment]
Hi @evbernardes ,

thanks for the hint. I will take a look.

**Comment by AlexanderFabisch** [comment]
Solved with #208
