### ISSUE TITLE
New logo

### ISSUE THREAD

**Issue by oarriaga** [dfki-ric/pytransform3d#246]
Hi thank you so much for this awesome library! 

I saw last week that you wanted help with the logo https://github.com/dfki-ric/pytransform3d/issues/241

I made this small logo with my renderer in case you want to use it. I can send you the script in case you want to change something!

![pytransform3D_logo](https://user-images.githubusercontent.com/5577137/233833062-a3196e5d-ceb4-4dd5-8315-2bc01ff3ffe8.png)

**Comment by AlexanderFabisch** [comment]
Awesome work, I will integrate it in the next version of the logo. :)

**Comment by AlexanderFabisch** [comment]
It's in the develop branch for 3.3.0
