### ISSUE TITLE
remove_transform introduces inconsistencies

### ISSUE THREAD

**Issue by matthaus-arrival** [dfki-ric/pytransform3d#252]
It seems the self.transform_to_ij_index is not updated when removing a transform, leading to inconsistencies and 'crashes':

```
import numpy as np
from pytransform3d.transform_manager import TransformManager

tm.add_transform('a', 'b', np.eye(4))
tm.add_transform('c', 'd', np.eye(4))
tm.remove_transform('a', 'b')
tm.remove_transform('c', 'd')
```

```
  File "~/.local/lib/python3.8/site-packages/pytransform3d/transform_manager.py", line 151, in remove_transform
    del self.i[ij_index]
IndexError: list assignment index out of range
```

**Comment by AlexanderFabisch** [comment]
That's interesting and obviously bad. Thanks for reporting @matthaus-arrival . I will take a look.

**Comment by AlexanderFabisch** [comment]
It is fixed on the develop branch now. I will make a new release (`3.2.0`) soon.

**Comment by matthaus-arrival** [comment]
Thanks for the fast action! And thanks for providing this great library!
