### ISSUE TITLE
Request: Interpolation method with linear displacement and SLERP rotation

### ISSUE THREAD

**Issue by scottshambaugh** [dfki-ric/pytransform3d#273]
I am just learning the library so apologies if there's an easy way to do this already. Looking [at the gallery example of interpolation methods](https://dfki-ric.github.io/pytransform3d/_auto_examples/plots/plot_dual_quaternion_interpolation.html#sphx-glr-auto-examples-plots-plot-dual-quaternion-interpolation-py) between two poses, I am looking for (and do not see) a trajectory that takes a straight line path. I am looking for an interpolation method that linearly interpolates the displacement, such that it follows the path of the black arrow in the image. And then the rotation along that trajectory would just be calculated with SLERP.

![image](https://github.com/dfki-ric/pytransform3d/assets/14363975/55269df7-55f3-4ce9-91c4-d813b42b9784)

Thank you for the library btw, I think that I'm going to find this immensely useful! I've picked up maintenance of the 3D plotting module of matplotlib so please don't hesitate to ping me on issues over there if there is something you're looking for.

**Comment by AlexanderFabisch** [comment]
> I am looking for (and do not see) a trajectory that takes a straight line path. I am looking for an interpolation method that linearly interpolates the displacement, such that it follows the path of the black arrow in the image. And then the rotation along that trajectory would just be calculated with SLERP.

Yes, that would be a useful feature. It's not directly available yet. Not sure for which representation I should make it available though. ScLERP is the natural interpolation for exp. coordinates and dual quaternions, but LERP + SLERP seems more appropriate for position + quaternion. What do you think?

> I've picked up maintenance of the 3D plotting module of matplotlib so please don't hesitate to ping me on issues over there if there is something you're looking for.

Thanks, that's good to know! :) Also feel free to let me know if there is something that can be improved in the usage of matplotlib for 3D plotting in pytransform3d.

**Comment by scottshambaugh** [comment]
I do think it makes most sense for the position + quaternion representation, yes. I don't know of a catchy name for it though :)

**Comment by AlexanderFabisch** [comment]
Released with 3.5.0 today
