### ISSUE TITLE
documentation in rotation matrix about column vector

### ISSUE THREAD

**Issue by vincentme** [dfki-ric/pytransform3d#321]
here [https://github.com/dfki-ric/pytransform3d/blob/main/doc/source/user_guide/rotations.rst](https://github.com/dfki-ric/pytransform3d/blob/main/doc/source/user_guide/rotations.rst), it says

> Each column of a rotation matrix \boldsymbol{R}_{BA} is a basis vector of frame B with respect to frame A.

However, this contradicts my understanding. By setting A_P to x basis vector (1, 0, 0) and multiply by R_BA, we got (R11, R21, R31), which is the first column of R_BA. The physical measning of this result is the **basis vector of frame A with respect to frame B**.

**Comment by AlexanderFabisch** [comment]
Correct. I recently updated the documentation to make the notation more consistent. I guess I introduced an error here. Thanks for reporting @vincentme . Would you like to make a pull request or should I update it?

**Comment by vincentme** [comment]
> Correct. I recently updated the documentation to make the notation more consistent. I guess I introduced an error here. Thanks for reporting @vincentme . Would you like to make a pull request or should I update it?

Thanks for comfirming! Pull request created.

**Comment by AlexanderFabisch** [comment]
Fixed with #322 . Thanks a lot!
