### ISSUE TITLE
[new feature] option to visualize offset coordinates

### ISSUE THREAD

**Issue by xmba15** [dfki-ric/pytransform3d#42]
Hi. I am trying to use pytransform3d.
Do you think it might be helpful to have an option to draw the coordinates of the origin on the 3d grid?
Something like this.
![Figure_1](https://user-images.githubusercontent.com/18694765/76144614-88502900-60c5-11ea-9866-15537f4f0f2c.png)

**Comment by AlexanderFabisch** [comment]
Hi @xmba15,

sounds good, but it should look more like this:

https://i.stack.imgur.com/CuBnn.png

**Comment by AlexanderFabisch** [comment]
Sorry, I misunderstood your suggestion. Yes, having an option to draw the coordinates of the origin would be nice, too. It be better to not draw it directly on the axes though.
