### ISSUE TITLE
use arrows instead of lines for transformation visualization, legend

### ISSUE THREAD

**Issue by theRealSuperMario** [dfki-ric/pytransform3d#55]
In most other 3D pipelines, coordinate transforms are represented as arrows instead of lines. It would be nice to have this here too, because it shows much more clearly what is going on.

It would also be great to have a functionality to return a color legend for the axis plots so that one does not have to guess which axis is which.

I could quickly prototype this, if desired.

**Comment by AlexanderFabisch** [comment]
Coming from a robotics background, I'm so used to lines instead of arrows (for example, in [ROS tf](http://wiki.ros.org/tf/Tutorials)) that I didn't even notice the difference. Indeed, arrows might look better in some situations. 3D matplotlib arrows are a bit ugly sometimes though. Go ahead if you want to prove me wrong. We could offer it as an additional function or include it as an option to `plot_basis()`.

**Comment by theRealSuperMario** [comment]
I just realized why I wanted this feature:

When names are provided and plottet , an additional black line is drawn that connets the text with the center of the coordinates. To me, this is kind of confusing becaues it is visually indistinguishable from the coordinate lines.

To fix this, we could
* make the line dottet
* make the line smaller
* draw arrows instead of lines for the axes
* a combination of the above.

I will experiment with these ideas and see what I like best. I know that this is a very tiny detail, however, as the number of transformations increases it is crucial to have a very clear and uncluttered visualization IMO.

**Comment by AlexanderFabisch** [comment]
> I know that this is a very tiny detail, however, as the number of transformations increases it is crucial to have a very clear and uncluttered visualization IMO.

That is perfectly fine. I like nitpicking. ;)

**Comment by AlexanderFabisch** [comment]
@theRealSuperMario Did you make any progress?

**Comment by theRealSuperMario** [comment]
Sorry I had to focus on some other things first. I'll need some more time.

**Comment by AlexanderFabisch** [comment]
No problem. I just wanted to know if you are still interested or if it is forgotten.
